AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: ''

Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: true
      Type: Canary10Percent5Minutes
      Role: !Ref CodeDeployRole

Resources:
  VseZaZabavoAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
      Auth:
        DefaultAuthorizer: VseZaZabavoAuthorizer
        Authorizers:
          VseZaZabavoAuthorizer:
            UserPoolArn: !GetAtt VseZaZabavoPool.Arn

  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambdas/main
      FunctionName: !Sub '${ProjectId}-lambda-Main'
      Handler: index.handler
      Runtime: python3.8
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetMain:
          Type: Api
          Properties:
            RestApiId: !Ref VseZaZabavoAPI
            Path: /
            Method: get
        PostMain:
          Type: Api
          Properties:
            RestApiId: !Ref VseZaZabavoAPI
            Path: /
            Method: post
        DynMain:
          Type: Api
          Properties:
            RestApiId: !Ref VseZaZabavoAPI
            Path: /main/{tukiID}
            Method: get

  ProstoriFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambdas/prostori
      FunctionName: !Sub '${ProjectId}-lambda-Prostori'
      Handler: index.handler
      Runtime: python3.8
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetProstori:
          Type: Api
          Properties:
            RestApiId: !Ref VseZaZabavoAPI
            Path: /prostori
            Method: get
            Auth:
              Authorizer: NONE
        PostProstori:
          Type: Api
          Properties:
            RestApiId: !Ref VseZaZabavoAPI
            Path: /prostori
            Method: post
        GetProstor:
          Type: Api
          Properties:
            RestApiId: !Ref VseZaZabavoAPI
            Path: /prostori/{prostorId}
            Method: get
            Auth:
              Authorizer: NONE
        PutProstor:
          Type: Api
          Properties:
            RestApiId: !Ref VseZaZabavoAPI
            Path: /prostori/{prostorId}
            Method: put
        DeleteProstor:
          Type: Api
          Properties:
            RestApiId: !Ref VseZaZabavoAPI
            Path: /prostori/{prostorId}
            Method: delete

  LambdaExecutionRole:
    Description: Creating service role in IAM for AWS Lambda
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'CodeStar-${ProjectId}-Execution${Stage}'
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        #- !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaDynamoDBExecutionRole'
      PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/CodeStar_${ProjectId}_PermissionsBoundary'

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: id_prostora
          AttributeType: S
        - AttributeName: user
          AttributeType: S
      KeySchema: 
        - AttributeName: id_prostora
          KeyType: HASH
        - AttributeName: user
          KeyType: RANGE
      #ProvisionedThroughput: 
      #  ReadCapacityUnits: 5
      #  WriteCapacityUnits: 5
      BillingMode: PAY_PER_REQUEST

  S3Bucket:  
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: vsezazabavo
      WebsiteConfiguration:
        IndexDocument: index.html

  VseZaZabavoPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: VseZaZabavoPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false

  VseZaZabavoPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref VseZaZabavoPool
      ClientName: VseZaZabavoPoolClient
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlows: 
        - code
        - implicit
      CallbackURLs:
        - http://localhost/vsezazabavo/callback.php
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - aws.cognito.signin.user.admin
        - profile
      GenerateSecret: false

  VseZaZabavoPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: vsezazabavo
      UserPoolId: !Ref VseZaZabavoPool